containerPort: 8082


httpHostname: inova-api-java-motor-carters.k8s-corp.riachuelo.net.br
httpsHostname: inova-api-java-motor-carters.k8s-corp.riachuelo.net.br
k8sContext: eks-shared-prod-rchlo-corp
tlsSecretName: eks-shared-prod-rchlo-corp    




initialReplicas: 2
configMapKeys: []
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8082
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8082
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
resources:
  requests:
    memory: 256M
    cpu: 150m
  limits:
    memory: 512M
    cpu: 1000m
hpa:
  maxReplicas: 4
  minReplicas: 2
  targetCPUUtilizationPercentage: 75
